kind: Service
apiVersion: v1
metadata:
  name: queue-punthai-backend-api-service
  namespace: queue-punthai
spec:
  type: LoadBalancer
  #ClusterIP
  #LoadBalancer
  #NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: queue-punthai-backend-api