apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-queue-configmap
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "UrlEndPoint": {
        "BaseApi": "http://localhost:53816/"
      },
      "ConnectionStrings" : {
        "DbConnection":"Data Source=server-sql-all-uat.database.windows.net;Initial Catalog=UAT-QUEUE-PUNTHAI; Persist Security Info=True;User ID=queue_punthai_app;Password=NrP95J^P9dfv9SgV?A=s2x-X"
      },
      "BlobConnectionString": "uat-queuepunthai-web-asv.azurewebsites.net",
      "BlobContainerName": "Filecontainer",
      "BlobSASTOKEN": "C3AA5SKNbqHPvP1qQkAFV8ooMdGTk3gUKdpPHGf9R4IxaW5wRsdO/d/3RCa575bI/Uf5i5dQ5HYb+ASt514rGQ=="
    }