kind: Deployment
apiVersion: apps/v1
metadata:
  name: queue-punthai-backend-api
  namespace: queue-punthai-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: queue-punthai-backend-api
  template:
    metadata:
      labels:
        app: queue-punthai-backend-api
    spec:
      serviceAccountName: queue-punthai-backend
      containers:
        - name: queue-punthai-backend-api
          image: devuatqueuepunthai.azurecr.io/queue-punthai-api:1.0.4.8
          volumeMounts:
          - name: appsetting
            mountPath: /app/appsettings.Production.json
            subPath: appsettings.Production.json
            readOnly: false
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: TZ
            value: Asia/Bangkok            
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: queue-punthai-secret
      volumes:
        - name:  appsetting
          secret:
            secretName: queue-punthai-secret