apiVersion: v1
kind: Secret
metadata:
  name: queue-punthai-secret
  namespace: queue-punthai-dev
type: Opaque
stringData:
  appsettings.Production.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "allowedHosts":"*",
      "UrlEndPoint": {
        "BaseApi": "https://dev-queue-punthai.pt.co.th/queue/",
        "PunthaiApi": "https://dev-queue-punthai.pt.co.th/queue/api/v1",
        "SignedApi": "https://dev-queue-punthai.pt.co.th/queue/api/v1/Signed"
      },
      "ConnectionStrings" : {
        "DbConnection":"Data Source=server-sql-all-uat.database.windows.net;Initial Catalog=UAT-QUEUE-PUNTHAI; Persist Security Info=True;User ID=queue_punthai_app;Password=NrP95J^P9dfv9SgV?A=s2x-X"
      },
      "BlobConnectionString": "uat-queuepunthai-web-asv.azurewebsites.net",
      "BlobContainerName": "Filecontainer",
      "BlobSASTOKEN": "C3AA5SKNbqHPvP1qQkAFV8ooMdGTk3gUKdpPHGf9R4IxaW5wRsdO/d/3RCa575bI/Uf5i5dQ5HYb+ASt514rGQ=="
    }
