name: "UAT - EKS queue-punthai-backend"

# on:
#  push:
#    branches: [ uat ]
#    paths-ignore:
#      - '**.md'
#      - '.github/workflows/**'
#      - 'k8s_deployment/**'
#      - 'dockerfile'
#  pull_request:
#    branches: [ uat ]
#    paths-ignore:
#      - '**.md'
#      - '.github/workflows/**'
#      - 'k8s_deployment/**'
#      - 'dockerfile'
#  workflow_dispatch:

# on: workflow_dispatch
on:
  pull_request:
   branches: [ uat ]
   paths-ignore:
     - '**.md'
     - '.github/workflows/**'
     - 'k8s_deployment/**'
     - 'dockerfile'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags Image'

env:
  APP_NAME: ${{ vars.APP_NAME }}
  APP_VERSION: ${{ vars.APP_VERSION }}
  AWS_REGION: "ap-southeast-1"
  AWS_ACCESS_KEY: ${{ secrets.PUNTHAI_UAT_QAS_AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.PUNTHAI_UAT_QAS_AWS_SECRET_KEY }}
  ECR_ACCESS_KEY: ${{ secrets.SHARED_AWS_ACCESS_KEY }}
  ECR_SECRET_KEY: ${{ secrets.SHARED_AWS_SECRET_KEY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  EKS_CUSTER_NAME: "uat-qas-punthai"
  IMAGE_TAG: ${{ github.run_number }}
  ENV_TAG: "uat"

jobs:

  # job_approval:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Manual Workflow Approval
  #     uses: trstringer/manual-approval@v1.9.0
  #     with:
  #       secret: ${{ github.TOKEN }}
  #       approvers: thavornch, lasttom
  #       minimum-approvals: 1
  #       issue-title: "Start Deploying"
  #       issue-body: "Please approve or deny the Start Deploying"
  #       exclude-workflow-initiator-as-approver: false
  #       additional-approved-words: ''
  #       additional-denied-words: ''

  job_build:
    name: "CI Dotnet restore package"
    runs-on: ubuntu-latest
    # needs: [job_approval]  
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build Dot net
    #   run: dotnet build --no-restore

    # - name: Unit Test
    #   run: dotnet test --no-build --verbosity normal
                
  job_ecr:
    needs: [job_build]
    if: ${{ needs.job_build.result == 'success' }}
    name: "Build image AWS ECR"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: "AWS credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.ECR_ACCESS_KEY }}
        aws-secret-access-key: ${{ env.ECR_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: "Login to Amazon ECR"
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker Tag and Push
      env:
        ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo ${{ steps.login_ecr.outputs.registry }}
        docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}${{ env.IMAGE_TAG }} .
        docker tag ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}${{ env.IMAGE_TAG }} ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}${{ env.IMAGE_TAG }}
        docker tag ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}${{ env.IMAGE_TAG }} ${{ env.ECR_REPOSITORY }}:${{ env.ENV_TAG }}
        docker tag ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}${{ env.IMAGE_TAG }} ${{ env.ECR_REPOSITORY }}:latest
        docker push ${{ env.ECR_REPOSITORY }}:${{ env.APP_VERSION }}${{ env.IMAGE_TAG }}
        docker push ${{ env.ECR_REPOSITORY }}:${{ env.ENV_TAG }}
        docker push ${{ env.ECR_REPOSITORY }}:latest
      if: success()
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}

  job_kubectl:
    permissions:
      actions: read
      contents: read
      id-token: write  
    name: "AWS credentials Kubectl"
    runs-on: ubuntu-latest
    needs: [job_ecr]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install and configure AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
        if: success()

      - name: EKS Kube config
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CUSTER_NAME }}
          aws eks list-clusters

      - name: Tag Image deployment
        run: |
          echo ${{ needs.job_ecr.login-ecr.outputs.registry }}
          sed -i 's|IMAGE_NAME|${{ needs.job_ecr.login-ecr.outputs.registry }}:${{ env.APP_VERSION }}${{ env.IMAGE_TAG }}|g' .github/k8s_uat/deployment.yaml
          cat .github/k8s_uat/deployment.yaml

      - name: AKS kubectl apply
        run: |
          kubectl apply -f .github/k8s_uat/namespace.yaml
          kubectl apply -f .github/k8s_uat/secret.yaml
          kubectl apply -f .github/k8s_uat/deployment.yaml
          kubectl apply -f .github/k8s_uat/service.yaml
          kubectl apply -f .github/k8s_uat/ingress.yaml
          kubectl apply -f .github/k8s_uat/hpa.yaml
